<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>LethalTweaks</AssemblyName>
    <Authors>MikeMediaStudios, Fake Game Developers</Authors>
    <Description>Continuation of MikesTweaks by MikeMediaStudios (MikeS-MS). Configurable item weights, item prices, inventory slots, keybinds, stamina, and moon costs.</Description>
    <Version>2.0.4</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <ThunderstorePackable>true</ThunderstorePackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Text.Json" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
</Project>
